apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  goTemplate: True
  goTemplateOptions: ["missingkey=error"]
  generators:
    # Merge can't use goTemplate for nested mergeKeys (seems very limiting with how generators are defined)
    # Workaround use matrix generators to generate top level keys from goTemplates, will be nicer if they fix it
    - merge:
        mergeKeys:
          - service
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: git@github.com:tallen12/gitops_k3s_infra.git
                    revision: HEAD
                    directories:
                    - path: infrastructure/*/base
                    values:
                      service: '{{index .path.segments 1}}'
                      overlay: '{{.path.basename}}'
                      url: "git@github.com:tallen12/gitops_k3s_infra.git"
                      basePath: '{{.path}}'
                - list:
                    elements:
                      - service: '{{index .path.segments 1}}'
          - matrix:
              generators:
                - git:
                    repoURL: git@github.com:tallen12/private_k3s_configs.git
                    revision: HEAD
                    directories:
                    - path: infrastructure/*/local
                    values:
                      service: '{{index .path.segments 1}}'
                      overlay: '{{.path.basename}}'
                      overlayUrl: 'git@github.com:tallen12/private_k3s_configs.git'
                      overlayPath: '{{.path}}'
                - list:
                    elements:
                      - service: '{{index .path.segments 1}}'
  template:
    metadata:
      name: '{{ .values.service }}'
      labels:
        infra-service: '{{ .values.service }}'
        overlay: '{{.values.overlay}}'
    spec:
      project: default
      ignoreDifferences:
        # Ignore specific fields within the ExternalSecret resource
        - kind: ExternalSecret
          jsonPointers:
            - /spec/refreshInterval
            - /status
            - /metadata/annotations/
            - /metadata/creationTimestamp
            - /metadata/generation
            - /metadata/resourceVersion
            - /metadata/uid
      destination:
        name: in-cluster
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
  templatePatch: |
    spec:
      {{- if .values.overlayUrl}}
      sources:
        - repoURL: '{{.values.url}}'
          path: '{{.values.basePath}}'
          targetRevision: main
        - repoURL: '{{.values.overlayUrl}}'
          path: '{{.values.overlayPath}}'
          targetRevision: main
      {{- else}}
      source:
        repoURL: '{{.values.url}}'
        targetRevision: main
        path: '{{.path.path}}'
      {{- end}}