apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-auth
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: database-storage
            operator: In
            values:
            - "true"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "1Gb"

    # Require 1Gi of space
  storage:
    size: 1Gi
    storageClass: postgres-longhorn-storage-class
