apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system
resources:
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v8.2.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v8.2.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v8.2.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.11.2/deploy/longhorn.yaml
  - storage-class.yaml

patches:
  - path: patches/default-setting-patch.yaml
  - target:
      kind: Namespace
      name: longhorn-system
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: longhorn-system
        labels:
          istio.io/dataplane-mode: ambient