apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-storage-class
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Replace=true
provisioner: driver.longhorn.io
reclaimPolicy: Delete
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-longhorn-storage-class
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Replace=true
provisioner: driver.longhorn.io
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  numberOfReplicas: "1"
  dataLocality: "strict-local"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: observability-longhorn-storage-class
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  dataLocality: "disabled"
  staleReplicaTimeout: "2880"
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
