apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-k3s

  target:
    name: operator-oauth    # must match the name the operator expects
    creationPolicy: Owner

  data:
    - secretKey: client_id       # key inside the k8s Secret
      remoteRef:
        key: "k8s tailscale oauth secret"
        property: "client id"             # field within that secret (omit for single-value)

    - secretKey: client_secret
      remoteRef:
        key: "k8s tailscale oauth secret"
        property: credential
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None