
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- external-operator-oauth-secret.yaml
- https://github.com/tailscale/tailscale/raw/main/cmd/k8s-operator/deploy/manifests/operator.yaml

patches:
  - path: remove-operator-oauth-secret.yaml