apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  # name of the ExternalSecret & Secret which gets created
  name: cloudflare-ini
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-k3s
  target:
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
  data:
  - secretKey: sshPrivateKey
    remoteRef:
      key: "Argocd github key"
      property: private key
