apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: loki
    repo: oci://ghcr.io/grafana-community/helm-charts/
    version: "17.1.1"
    releaseName: loki
    namespace: monitoring
    valuesFile: values.yaml
